2017-04-27 13:56:56,476 [ERROR] from play.core.server.NettyServer in pool-5-thread-3 - Failed to listen for HTTP on /0.0.0.0:8000!
2017-04-27 23:15:45,194 [ERROR] from io.netty.util.concurrent.DefaultPromise.rejectedExecution in pool-555-thread-1 - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:805) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1005) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:614) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:469) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:949) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:194) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.pool.SimpleChannelPool.close(SimpleChannelPool.java:345) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [scala-library-2.11.7.jar:1.0.1]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ServiceGateway.scala:361) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) [scala-library-2.11.7.jar:1.0.1]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:1.0.1]
	at scala.util.Success.map(Try.scala:237) [scala-library-2.11.7.jar:1.0.1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.5.10.jar:2.5.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.5.10.jar:2.5.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:333) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$class.flatMap(Future.scala:249) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$KeptPromise.flatMap(Promise.scala:322) [scala-library-2.11.7.jar:na]
	at play.api.inject.DefaultApplicationLifecycle.clearHooks$1(ApplicationLifecycle.scala:93) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.inject.DefaultApplicationLifecycle.stop(ApplicationLifecycle.scala:101) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.DefaultApplication.stop(Application.scala:236) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:128) [play_2.11-2.5.10.jar:2.5.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.Play$.stop(Play.scala:126) [play_2.11-2.5.10.jar:2.5.10]
	at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at scala.Option.foreach(Option.scala:257) [scala-library-2.11.7.jar:1.0.1]
	at play.core.server.NettyServer.stop(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at com.lightbend.lagom.discovery.ServiceLocatorServer.close(ServiceLocatorServer.scala:67) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServiceLocator$.com$lightbend$lagom$dev$Servers$ServiceLocator$$stop(Servers.scala:129) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServiceLocator$.stop(Servers.scala:124) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServerContainer.tryStop(Servers.scala:75) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply$mcV$sp(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-05-03 18:15:01,626 [ERROR] from io.netty.util.concurrent.DefaultPromise.rejectedExecution in pool-122-thread-1 - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:805) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748) ~[netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120) [netty-common-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1005) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:614) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:469) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:949) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:194) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at io.netty.channel.pool.SimpleChannelPool.close(SimpleChannelPool.java:345) [netty-transport-4.0.41.Final.jar:4.0.41.Final]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [scala-library-2.11.7.jar:1.0.1]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [scala-library-2.11.7.jar:1.0.1]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ServiceGateway.scala:364) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.gateway.ServiceGateway$$anonfun$1$$anonfun$apply$2$$anonfun$apply$3.apply(ServiceGateway.scala:361) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) [scala-library-2.11.7.jar:1.0.1]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:1.0.1]
	at scala.util.Success.map(Try.scala:237) [scala-library-2.11.7.jar:1.0.1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.5.10.jar:2.5.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.5.10.jar:2.5.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:333) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$class.flatMap(Future.scala:249) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$KeptPromise.flatMap(Promise.scala:322) [scala-library-2.11.7.jar:na]
	at play.api.inject.DefaultApplicationLifecycle.clearHooks$1(ApplicationLifecycle.scala:93) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.inject.DefaultApplicationLifecycle.stop(ApplicationLifecycle.scala:101) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.DefaultApplication.stop(Application.scala:236) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:128) [play_2.11-2.5.10.jar:2.5.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.5.10.jar:2.5.10]
	at play.api.Play$.stop(Play.scala:126) [play_2.11-2.5.10.jar:2.5.10]
	at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at scala.Option.foreach(Option.scala:257) [scala-library-2.11.7.jar:1.0.1]
	at play.core.server.NettyServer.stop(NettyServer.scala:247) [play-netty-server_2.11-2.5.10.jar:2.5.10]
	at com.lightbend.lagom.discovery.ServiceLocatorServer.close(ServiceLocatorServer.scala:67) [lagom-service-locator_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServiceLocator$.com$lightbend$lagom$dev$Servers$ServiceLocator$$stop(Servers.scala:129) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServiceLocator$.stop(Servers.scala:124) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$ServerContainer.tryStop(Servers.scala:75) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply$mcV$sp(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.dev.Servers$$anonfun$1$$anonfun$apply$1.apply(Servers.scala:29) [lagom-build-tool-support-1.3.2.jar:1.3.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
2017-05-05 22:59:42,600 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170505225927786-akka.actor.default-dispatcher-2 - Processor actor [Actor[akka://ServiceTest_170505225927786/user/StreamSupervisor-0/flow-2-1-unknown-operation#-2046341762]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170505225927786/user/StreamSupervisor-0/flow-2-1-unknown-operation#-2046341762]] terminated abruptly
2017-05-06 01:04:57,680 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506010445678-akka.actor.default-dispatcher-4 - Processor actor [Actor[akka://ServiceTest_170506010445678/user/StreamSupervisor-0/flow-3-1-unknown-operation#982294638]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506010445678/user/StreamSupervisor-0/flow-3-1-unknown-operation#982294638]] terminated abruptly
2017-05-06 14:45:34,541 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506144516710-akka.actor.default-dispatcher-3 - Recipient[Actor[akka://ServiceTest_170506144516710/user/readSideGlobalPrepare-TaskEventProcessor-singletonProxy#-2034598221]] had already been terminated. Sender[null] sent the message of type "com.lightbend.lagom.internal.persistence.cluster.ClusterStartupTaskActor$Execute$".
akka.pattern.AskTimeoutException: Recipient[Actor[akka://ServiceTest_170506144516710/user/readSideGlobalPrepare-TaskEventProcessor-singletonProxy#-2034598221]] had already been terminated. Sender[null] sent the message of type "com.lightbend.lagom.internal.persistence.cluster.ClusterStartupTaskActor$Execute$".
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:289) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.pattern.AskableActorRef$.$qmark$extension1(AskSupport.scala:281) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.persistence.cluster.ClusterStartupTask.askExecute(ClusterStartupTask.scala:84) ~[lagom-persistence-core_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.internal.javadsl.persistence.ReadSideActor$$anonfun$receive$1.applyOrElse(ReadSideActor.scala:65) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.ReadSideActor.aroundReceive(ReadSideActor.scala:40) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 14:48:19,475 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506144801386-akka.actor.default-dispatcher-15 - Processor actor [Actor[akka://ServiceTest_170506144801386/user/StreamSupervisor-0/flow-3-1-unknown-operation#-1756355266]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506144801386/user/StreamSupervisor-0/flow-3-1-unknown-operation#-1756355266]] terminated abruptly
2017-05-06 14:51:43,764 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506145122924-akka.actor.default-dispatcher-19 - Processor actor [Actor[akka://ServiceTest_170506145122924/user/StreamSupervisor-0/flow-2-1-unknown-operation#473889142]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506145122924/user/StreamSupervisor-0/flow-2-1-unknown-operation#473889142]] terminated abruptly
2017-05-06 14:57:54,378 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506145737948-akka.actor.default-dispatcher-4 - Processor actor [Actor[akka://ServiceTest_170506145737948/user/StreamSupervisor-0/flow-3-1-unknown-operation#269937007]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506145737948/user/StreamSupervisor-0/flow-3-1-unknown-operation#269937007]] terminated abruptly
2017-05-06 15:04:07,750 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506150353058-akka.actor.default-dispatcher-18 - Processor actor [Actor[akka://ServiceTest_170506150353058/user/StreamSupervisor-0/flow-3-1-unknown-operation#1430636321]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506150353058/user/StreamSupervisor-0/flow-3-1-unknown-operation#1430636321]] terminated abruptly
2017-05-06 15:14:14,850 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151402398-akka.actor.default-dispatcher-15 - null
java.lang.NullPointerException: null
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:66) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:64) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.cluster.sharding.ShardRegion.deliverMessage(ShardRegion.scala:696) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion$$anonfun$receive$2.applyOrElse(ShardRegion.scala:417) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion.aroundReceive(ShardRegion.scala:339) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:14:19,856 [ERROR] from task in ServiceTest_170506151402398-akka.actor.default-dispatcher-16 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ServiceTest_170506151402398/system/sharding/TaskEntity#-1599329260]] after [5000 ms]. Sender[null] sent message of type "com.lightbend.lagom.javadsl.persistence.CommandEnvelope".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[scala-library-2.11.8.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236) ~[akka-actor_2.11-2.4.17.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
2017-05-06 15:14:19,957 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151402398-akka.actor.default-dispatcher-4 - Processor actor [Actor[akka://ServiceTest_170506151402398/user/StreamSupervisor-0/flow-3-1-unknown-operation#-605555777]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506151402398/user/StreamSupervisor-0/flow-3-1-unknown-operation#-605555777]] terminated abruptly
2017-05-06 15:15:47,489 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151531958-akka.actor.default-dispatcher-14 - null
java.lang.NullPointerException: null
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:66) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:64) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.cluster.sharding.ShardRegion.deliverMessage(ShardRegion.scala:696) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion$$anonfun$receive$2.applyOrElse(ShardRegion.scala:417) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion.aroundReceive(ShardRegion.scala:339) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:15:52,496 [ERROR] from task in ServiceTest_170506151531958-akka.actor.default-dispatcher-20 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ServiceTest_170506151531958/system/sharding/TaskEntity#-274618504]] after [5000 ms]. Sender[null] sent message of type "com.lightbend.lagom.javadsl.persistence.CommandEnvelope".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[scala-library-2.11.8.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236) ~[akka-actor_2.11-2.4.17.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
2017-05-06 15:15:52,666 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151531958-akka.actor.default-dispatcher-20 - Processor actor [Actor[akka://ServiceTest_170506151531958/user/StreamSupervisor-0/flow-3-1-unknown-operation#445866243]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506151531958/user/StreamSupervisor-0/flow-3-1-unknown-operation#445866243]] terminated abruptly
2017-05-06 15:18:05,476 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151748480-akka.actor.default-dispatcher-15 - null
java.lang.NullPointerException: null
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:66) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at com.lightbend.lagom.internal.javadsl.persistence.AbstractPersistentEntityRegistry$$anonfun$2.apply(AbstractPersistentEntityRegistry.scala:64) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.cluster.sharding.ShardRegion.deliverMessage(ShardRegion.scala:696) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion$$anonfun$receive$2.applyOrElse(ShardRegion.scala:417) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.cluster.sharding.ShardRegion.aroundReceive(ShardRegion.scala:339) ~[akka-cluster-sharding_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:18:10,487 [ERROR] from task in ServiceTest_170506151748480-akka.actor.default-dispatcher-20 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ServiceTest_170506151748480/system/sharding/TaskEntity#-1103399033]] after [5000 ms]. Sender[null] sent message of type "com.lightbend.lagom.javadsl.persistence.CommandEnvelope".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[scala-library-2.11.8.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236) ~[akka-actor_2.11-2.4.17.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
2017-05-06 15:18:10,645 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506151748480-akka.actor.default-dispatcher-16 - Processor actor [Actor[akka://ServiceTest_170506151748480/user/StreamSupervisor-0/flow-3-1-unknown-operation#1648516031]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506151748480/user/StreamSupervisor-0/flow-3-1-unknown-operation#1648516031]] terminated abruptly
2017-05-06 15:34:18,308 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506153402661-akka.actor.default-dispatcher-14 - Processor actor [Actor[akka://ServiceTest_170506153402661/user/StreamSupervisor-0/flow-3-1-unknown-operation#305985297]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506153402661/user/StreamSupervisor-0/flow-3-1-unknown-operation#305985297]] terminated abruptly
2017-05-06 15:40:08,197 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506153948462-akka.actor.default-dispatcher-20 - Processor actor [Actor[akka://ServiceTest_170506153948462/user/StreamSupervisor-0/flow-3-1-unknown-operation#428877708]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506153948462/user/StreamSupervisor-0/flow-3-1-unknown-operation#428877708]] terminated abruptly
2017-05-06 15:44:37,176 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506154417287-akka.actor.default-dispatcher-3 - Processor actor [Actor[akka://ServiceTest_170506154417287/user/StreamSupervisor-0/flow-3-1-unknown-operation#856556632]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506154417287/user/StreamSupervisor-0/flow-3-1-unknown-operation#856556632]] terminated abruptly
2017-05-06 15:48:21,098 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506154800357-akka.actor.default-dispatcher-3 - Processor actor [Actor[akka://ServiceTest_170506154800357/user/StreamSupervisor-0/flow-2-1-unknown-operation#-441774013]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506154800357/user/StreamSupervisor-0/flow-2-1-unknown-operation#-441774013]] terminated abruptly
2017-05-06 15:50:26,855 [ERROR] from task in ServiceTest_170506155011372-akka.actor.default-dispatcher-4 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:50:32,220 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506155011372-akka.actor.default-dispatcher-20 - Processor actor [Actor[akka://ServiceTest_170506155011372/user/StreamSupervisor-0/flow-3-1-unknown-operation#689472034]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506155011372/user/StreamSupervisor-0/flow-3-1-unknown-operation#689472034]] terminated abruptly
2017-05-06 15:54:20,300 [ERROR] from task in ServiceTest_170506155405620-akka.actor.default-dispatcher-14 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:54:25,528 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506155405620-akka.actor.default-dispatcher-14 - Processor actor [Actor[akka://ServiceTest_170506155405620/user/StreamSupervisor-0/flow-3-1-unknown-operation#-1511505434]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506155405620/user/StreamSupervisor-0/flow-3-1-unknown-operation#-1511505434]] terminated abruptly
2017-05-06 15:57:52,262 [ERROR] from task in ServiceTest_170506155739602-akka.actor.default-dispatcher-14 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:57:57,490 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506155739602-akka.actor.default-dispatcher-19 - Processor actor [Actor[akka://ServiceTest_170506155739602/user/StreamSupervisor-0/flow-3-1-unknown-operation#-571751225]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506155739602/user/StreamSupervisor-0/flow-3-1-unknown-operation#-571751225]] terminated abruptly
2017-05-06 15:59:06,358 [ERROR] from task in ServiceTest_170506155852038-akka.actor.default-dispatcher-14 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 15:59:21,630 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506155852038-akka.actor.default-dispatcher-19 - Processor actor [Actor[akka://ServiceTest_170506155852038/user/StreamSupervisor-0/flow-3-1-unknown-operation#1284131405]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506155852038/user/StreamSupervisor-0/flow-3-1-unknown-operation#1284131405]] terminated abruptly
2017-05-06 16:02:27,492 [ERROR] from task in ServiceTest_170506160207793-akka.actor.default-dispatcher-16 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 16:02:32,604 [ERROR] from task in ServiceTest_170506160207793-akka.actor.default-dispatcher-17 - Exception in RestCallId{method=PUT, pathPattern='/api/task/:id'}
UpdateFailureException: Invalid state submited for the task.
	at UpdateFailureException.<clinit>(UpdateFailureException.java:8) ~[classes/:na]
	at TaskEntity.lambda$initialBehavior$4(TaskEntity.java:48) ~[classes/:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor$$anonfun$receiveCommand$1.applyOrElse(PersistentEntityActor.scala:136) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497) ~[akka-actor_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664) ~[akka-persistence_2.11-2.4.17.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183) ~[akka-persistence_2.11-2.4.17.jar:na]
	at com.lightbend.lagom.internal.javadsl.persistence.PersistentEntityActor.aroundReceive(PersistentEntityActor.scala:49) ~[lagom-javadsl-persistence_2.11-1.3.2.jar:1.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
2017-05-06 16:02:42,799 [ERROR] from akka.actor.OneForOneStrategy in ServiceTest_170506160207793-akka.actor.default-dispatcher-20 - Processor actor [Actor[akka://ServiceTest_170506160207793/user/StreamSupervisor-0/flow-3-1-unknown-operation#-984648247]] terminated abruptly
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ServiceTest_170506160207793/user/StreamSupervisor-0/flow-3-1-unknown-operation#-984648247]] terminated abruptly
